#!/usr/bin/php
<?php

include "options.php";
include "my_scandir.php";
include "my_merge.php";


$folder_path = end($argv);

if($folder_path === "man") {
    echo file_get_contents("manual_css_generator.txt");
} else {
    $arr = my_scandir($folder_path, $is_recursive);

    echo "Les fichiers .png ont été récupérés dans le dossier choisi";
    echo (!$is_recursive) ? "\n" : " et ses sous-dossiers\n";

    my_merge_image($arr, $sprite_name, $css_name);
}